apiVersion: v1
kind: Service
metadata:
  name: veri-agent
  namespace: veri-agent
  labels:
    app.kubernetes.io/name: veri-agent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: veri-agent
  ports:
    - name: http
      port: 3040
      targetPort: http
      protocol: TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: veri-agent
  namespace: veri-agent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: veri-agent
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
