apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: veriforge-staging
resources:
  - namespace.yaml
  - ../../
patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
  - path: worker-rollout-patch.yaml
images:
  - name: ghcr.io/OWNER/veriforge-api
    newName: ghcr.io/OWNER/veriforge-api
    newTag: latest
  - name: ghcr.io/OWNER/veriforge-frontend
    newName: ghcr.io/OWNER/veriforge-frontend
    newTag: latest
