import { Injectable, Optional } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import type { SafetyFormDefinitionJson } from '../engine/form-engine.types';
import { FormCailBridgeService } from '../../safety-intelligence/forms/form-cail-bridge.service';

@Injectable()
export class SafetyFormCorrectiveActionsService {
  constructor(
    private readonly prisma: PrismaService,
    @Optional() private readonly formCail?: FormCailBridgeService,
  ) {}

  async generateFromForm(
    formId: string,
    definition: SafetyFormDefinitionJson,
    formData: Record<string, unknown>,
    companyId?: number | null,
    createdById?: number,
    projectId?: number | null,
    siteId?: number | null,
    workerId?: number | null,
    equipmentId?: number | null,
  ) {
    const shouldRun =
      definition.workflow?.autoGenerateCorrectiveActions ||
      definition.workflow?.autoGenerateCail;

    if (!shouldRun) return [];

    if (this.formCail && projectId) {
      const cailEntries = await this.formCail.emitFromSafetyForm(
        formId,
        definition,
        formData,
        {
          projectId,
          companyId,
          siteId,
          workerId,
          equipmentId,
          createdById,
        },
      );

      const actions = [];
      for (const cail of cailEntries) {
        const action = await this.prisma.safetyFormAction.create({
          data: {
            formId,
            title: cail.title,
            description: cail.description ?? undefined,
            autoGenerated: true,
            dueAt: cail.dueDate ?? undefined,
          },
        });
        actions.push({ ...action, cailEntryId: cail.id });
      }
      return actions;
    }

    return this.legacyCoreActionItems(
      formId,
      definition,
      formData,
      companyId,
      createdById,
    );
  }

  private async legacyCoreActionItems(
    formId: string,
    definition: SafetyFormDefinitionJson,
    formData: Record<string, unknown>,
    companyId?: number | null,
    createdById?: number,
  ) {
    const titles: string[] = [];
    if (formData.controlsAdequate === 'no' || formData.fitForUse === 'no') {
      titles.push('Address inadequate controls / equipment condition');
    }
    if (
      formData.complianceRating === 'major_issues' ||
      formData.complianceRating === 'stop_work'
    ) {
      titles.push('Correct major safety inspection findings');
    }
    if (formData.defectsFound && String(formData.defectsFound).trim()) {
      titles.push(
        `Correct defects: ${String(formData.defectsFound).slice(0, 80)}`,
      );
    }
    if (formData.correctiveAction && String(formData.correctiveAction).trim()) {
      titles.push(String(formData.correctiveAction).slice(0, 120));
    }
    if (!titles.length && formData.findingDescription) {
      titles.push(String(formData.findingDescription).slice(0, 120));
    }

    const created = [];
    for (const title of titles) {
      const action = await this.prisma.safetyFormAction.create({
        data: {
          formId,
          title,
          description:
            typeof formData.rootCause === 'string'
              ? formData.rootCause
              : undefined,
          autoGenerated: true,
          dueAt: formData.dueDate
            ? new Date(String(formData.dueDate))
            : undefined,
        },
      });

      const coreItem = await this.prisma.coreActionItem.create({
        data: {
          title,
          description: action.description ?? undefined,
          companyId: companyId ?? undefined,
          createdById: createdById ?? undefined,
          dueAt: action.dueAt ?? undefined,
          priority: 'NORMAL',
          status: 'OPEN',
        },
      });

      await this.prisma.safetyFormAction.update({
        where: { id: action.id },
        data: { coreActionItemId: coreItem.id },
      });

      created.push({ ...action, coreActionItemId: coreItem.id });
    }
    return created;
  }

  async listForForm(formId: string) {
    const actions = await this.prisma.safetyFormAction.findMany({
      where: { formId },
      orderBy: { createdAt: 'desc' },
    });

    const links = await this.prisma.safetyFormCailLink.findMany({
      where: { safetyFormId: formId },
      include: {
        cailEntry: { select: { id: true, title: true, status: true } },
      },
    });

    return { actions, cailLinks: links };
  }
}
