-- CreateEnum
CREATE TYPE "SafetyFormStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CLOSED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "SafetyFormSignatureRole" AS ENUM ('WORKER', 'SUPERVISOR', 'AUTHORIZER', 'WITNESS', 'OTHER');

-- CreateEnum
CREATE TYPE "SafetyFormActionStatus" AS ENUM ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');

-- CreateTable
CREATE TABLE "safety_form_definitions" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "definition" JSONB NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "companyId" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "safety_form_definitions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "safety_form_versions" (
    "id" TEXT NOT NULL,
    "definitionId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "definition" JSONB NOT NULL,
    "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "publishedBy" INTEGER,

    CONSTRAINT "safety_form_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "safety_forms" (
    "id" TEXT NOT NULL,
    "definitionId" TEXT NOT NULL,
    "definitionVersion" INTEGER NOT NULL DEFAULT 1,
    "status" "SafetyFormStatus" NOT NULL DEFAULT 'DRAFT',
    "title" TEXT,
    "formData" JSONB NOT NULL DEFAULT '{}',
    "sifFlag" BOOLEAN NOT NULL DEFAULT false,
    "hecaFlag" BOOLEAN NOT NULL DEFAULT false,
    "companyId" INTEGER,
    "projectId" INTEGER,
    "siteId" INTEGER,
    "workerId" INTEGER,
    "equipmentId" INTEGER,
    "incidentId" INTEGER,
    "createdById" INTEGER,
    "submittedById" INTEGER,
    "reviewedById" INTEGER,
    "submittedAt" TIMESTAMP(3),
    "reviewedAt" TIMESTAMP(3),
    "clientSyncId" TEXT,
    "clientVersion" INTEGER NOT NULL DEFAULT 0,
    "offlinePending" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "safety_forms_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "safety_form_submissions" (
    "id" TEXT NOT NULL,
    "formId" TEXT NOT NULL,
    "versionNumber" INTEGER NOT NULL,
    "formData" JSONB NOT NULL,
    "status" "SafetyFormStatus" NOT NULL,
    "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "submittedById" INTEGER,

    CONSTRAINT "safety_form_submissions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "safety_form_attachments" (
    "id" TEXT NOT NULL,
    "formId" TEXT NOT NULL,
    "fieldId" TEXT,
    "fileName" TEXT NOT NULL,
    "mimeType" TEXT,
    "storageKey" TEXT,
    "dataUrl" TEXT,
    "sizeBytes" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "safety_form_attachments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "safety_form_signatures" (
    "id" TEXT NOT NULL,
    "formId" TEXT NOT NULL,
    "fieldId" TEXT,
    "role" "SafetyFormSignatureRole" NOT NULL DEFAULT 'WORKER',
    "signerName" TEXT,
    "signerUserId" INTEGER,
    "signatureData" TEXT NOT NULL,
    "signedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "safety_form_signatures_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "safety_form_actions" (
    "id" TEXT NOT NULL,
    "formId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "status" "SafetyFormActionStatus" NOT NULL DEFAULT 'OPEN',
    "priority" TEXT NOT NULL DEFAULT 'NORMAL',
    "dueAt" TIMESTAMP(3),
    "assignedToId" INTEGER,
    "coreActionItemId" TEXT,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "safety_form_actions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "safety_form_audit_log" (
    "id" TEXT NOT NULL,
    "formId" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "actorId" INTEGER,
    "payload" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "safety_form_audit_log_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "safety_form_definitions_category_isActive_idx" ON "safety_form_definitions"("category", "isActive");

-- CreateIndex
CREATE INDEX "safety_form_definitions_companyId_idx" ON "safety_form_definitions"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "safety_form_versions_definitionId_version_key" ON "safety_form_versions"("definitionId", "version");

-- CreateIndex
CREATE INDEX "safety_form_versions_definitionId_version_idx" ON "safety_form_versions"("definitionId", "version");

-- CreateIndex
CREATE UNIQUE INDEX "safety_forms_clientSyncId_key" ON "safety_forms"("clientSyncId");

-- CreateIndex
CREATE INDEX "safety_forms_definitionId_status_idx" ON "safety_forms"("definitionId", "status");

-- CreateIndex
CREATE INDEX "safety_forms_companyId_status_updatedAt_idx" ON "safety_forms"("companyId", "status", "updatedAt");

-- CreateIndex
CREATE INDEX "safety_forms_projectId_status_idx" ON "safety_forms"("projectId", "status");

-- CreateIndex
CREATE INDEX "safety_forms_workerId_createdAt_idx" ON "safety_forms"("workerId", "createdAt");

-- CreateIndex
CREATE INDEX "safety_forms_siteId_status_idx" ON "safety_forms"("siteId", "status");

-- CreateIndex
CREATE UNIQUE INDEX "safety_form_submissions_formId_versionNumber_key" ON "safety_form_submissions"("formId", "versionNumber");

-- CreateIndex
CREATE INDEX "safety_form_submissions_formId_submittedAt_idx" ON "safety_form_submissions"("formId", "submittedAt");

-- CreateIndex
CREATE INDEX "safety_form_attachments_formId_idx" ON "safety_form_attachments"("formId");

-- CreateIndex
CREATE INDEX "safety_form_signatures_formId_idx" ON "safety_form_signatures"("formId");

-- CreateIndex
CREATE INDEX "safety_form_actions_formId_status_idx" ON "safety_form_actions"("formId", "status");

-- CreateIndex
CREATE INDEX "safety_form_audit_log_formId_createdAt_idx" ON "safety_form_audit_log"("formId", "createdAt");

-- AddForeignKey
ALTER TABLE "safety_form_definitions" ADD CONSTRAINT "safety_form_definitions_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_form_versions" ADD CONSTRAINT "safety_form_versions_definitionId_fkey" FOREIGN KEY ("definitionId") REFERENCES "safety_form_definitions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_forms" ADD CONSTRAINT "safety_forms_definitionId_fkey" FOREIGN KEY ("definitionId") REFERENCES "safety_form_definitions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_forms" ADD CONSTRAINT "safety_forms_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_forms" ADD CONSTRAINT "safety_forms_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_forms" ADD CONSTRAINT "safety_forms_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_forms" ADD CONSTRAINT "safety_forms_workerId_fkey" FOREIGN KEY ("workerId") REFERENCES "Worker"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_forms" ADD CONSTRAINT "safety_forms_equipmentId_fkey" FOREIGN KEY ("equipmentId") REFERENCES "Equipment"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_forms" ADD CONSTRAINT "safety_forms_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "Incident"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_forms" ADD CONSTRAINT "safety_forms_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_forms" ADD CONSTRAINT "safety_forms_submittedById_fkey" FOREIGN KEY ("submittedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_forms" ADD CONSTRAINT "safety_forms_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_form_submissions" ADD CONSTRAINT "safety_form_submissions_formId_fkey" FOREIGN KEY ("formId") REFERENCES "safety_forms"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_form_attachments" ADD CONSTRAINT "safety_form_attachments_formId_fkey" FOREIGN KEY ("formId") REFERENCES "safety_forms"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_form_signatures" ADD CONSTRAINT "safety_form_signatures_formId_fkey" FOREIGN KEY ("formId") REFERENCES "safety_forms"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_form_signatures" ADD CONSTRAINT "safety_form_signatures_signerUserId_fkey" FOREIGN KEY ("signerUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_form_actions" ADD CONSTRAINT "safety_form_actions_formId_fkey" FOREIGN KEY ("formId") REFERENCES "safety_forms"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_form_audit_log" ADD CONSTRAINT "safety_form_audit_log_formId_fkey" FOREIGN KEY ("formId") REFERENCES "safety_forms"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "safety_form_audit_log" ADD CONSTRAINT "safety_form_audit_log_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
