import { Injectable } from '@nestjs/common';
import {
  PmDeficiencySeverity,
  PmInspectionFindingCategory,
  PmInspectionResponsibleParty,
  Prisma,
} from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { PmCorrectiveActionsService } from '../pm-corrective-actions/pm-corrective-actions.service';
import { CapaDueDateEngine } from '../pm-corrective-actions/capa-due-date.engine';

export type StructuredFindingInput = {
  category: PmInspectionFindingCategory;
  title: string;
  description?: string;
  severity: PmDeficiencySeverity;
  confidence: number;
  responsibleParty: PmInspectionResponsibleParty;
  subcontractorCompanyId?: number;
  source?: 'llm' | 'rules';
};

const EVIDENCE_BY_CATEGORY: Record<PmInspectionFindingCategory, string[]> = {
  unsafe_condition: ['photo_after', 'supervisor_signoff'],
  missing_ppe: ['photo_compliance', 'training_record'],
  equipment_defect: ['photo_repair', 'maintenance_log'],
  housekeeping: ['photo_cleared'],
  environmental: ['photo_mitigation', 'monitoring_record'],
  other: ['photo_evidence'],
};

@Injectable()
export class PmInspectionFindingCapaService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly capa: PmCorrectiveActionsService,
    private readonly dueDate: CapaDueDateEngine,
  ) {}

  async generateFromFinding(input: {
    inspectionId: string;
    findingId: string;
    actorId: number;
    structured: StructuredFindingInput;
    attachmentId?: string;
  }) {
    const inspection = await this.prisma.pmInspection.findUnique({
      where: { id: input.inspectionId },
      include: { project: { select: { name: true } } },
    });
    if (!inspection) return null;

    const config = await this.capa.getCompanyConfig(inspection.companyId);
    const severityCail =
      input.structured.severity === 'critical'
        ? 'critical'
        : input.structured.severity === 'high'
        ? 'high'
        : input.structured.severity === 'low'
        ? 'low'
        : 'medium';
    const dueAt = this.dueDate.computeDueAt(severityCail, config);

    const evidenceRequired = EVIDENCE_BY_CATEGORY[
      input.structured.category
    ] ?? ['photo_evidence'];

    const deficiency = await this.prisma.pmInspectionDeficiency.create({
      data: {
        inspectionId: inspection.id,
        itemId: `photo_${input.findingId.slice(0, 8)}`,
        title: input.structured.title,
        description: input.structured.description,
        severity: input.structured.severity,
        category: input.structured.category,
        dueAt,
        autoGenerated: true,
        subcontractorCompanyId:
          input.structured.responsibleParty === 'contractor'
            ? input.structured.subcontractorCompanyId
            : undefined,
      },
    });

    const assignUserId =
      input.structured.responsibleParty === 'supervisor'
        ? input.actorId
        : undefined;

    const action = await this.capa.create({
      companyId: inspection.companyId,
      projectId: inspection.projectId,
      siteId: inspection.siteId ?? undefined,
      equipmentId: inspection.equipmentId ?? undefined,
      sourceModule: 'inspection',
      sourceId: inspection.id,
      sourceItemId: deficiency.id,
      deficiencyId: deficiency.id,
      title: input.structured.title,
      description: input.structured.description,
      actionType: 'permanent',
      severity: severityCail,
      createdByUserId: input.actorId,
      assignUserId,
      subcontractorCompanyId:
        input.structured.responsibleParty === 'contractor'
          ? input.structured.subcontractorCompanyId
          : undefined,
      workerId:
        input.structured.responsibleParty === 'worker'
          ? inspection.workerId ?? undefined
          : undefined,
      publish: true,
    });

    await this.prisma.pmCorrectiveAction.update({
      where: { id: action.id },
      data: {
        dueAt,
        evidenceRequirementsJson: {
          required: evidenceRequired,
          source: 'inspection_photo_pipeline',
        } as Prisma.InputJsonValue,
      },
    });

    await this.prisma.pmInspectionDeficiency.update({
      where: { id: deficiency.id },
      data: { cailEntryId: action.cailEntryId },
    });

    await this.prisma.pmInspectionPhotoFinding.update({
      where: { id: input.findingId },
      data: {
        deficiencyId: deficiency.id,
        correctiveActionId: action.id,
      },
    });

    return { deficiency, correctiveAction: action, dueAt, evidenceRequired };
  }
}
