-- PM Company Safety Context Engine

CREATE TYPE "PmCompanyHazardCategory" AS ENUM ('energy', 'environmental', 'equipment', 'chemical', 'behavioral', 'organizational');

-- CreateEnum
CREATE TYPE "PmCompanyControlType" AS ENUM ('engineering', 'administrative', 'ppe', 'procedural', 'equipment');

-- CreateEnum
CREATE TYPE "PmCompanyPolicyType" AS ENUM ('safety_policy', 'procedure', 'sop', 'manual', 'safety_bulletin', 'corporate_standard');

-- CreateEnum
CREATE TYPE "PmCompanyTrainingRoleType" AS ENUM ('worker', 'supervisor', 'subcontractor', 'equipment_operator', 'visitor');

-- CreateEnum
CREATE TYPE "PmCompanyTrainingCategory" AS ENUM ('general_safety', 'equipment_operation', 'high_risk_work', 'chemical_handling', 'emergency_response', 'company_specific');

-- CreateEnum
CREATE TYPE "PmCompanySafetyOverrideType" AS ENUM ('temporary', 'one_time', 'policy', 'training', 'equipment', 'zone');

-- CreateEnum
CREATE TYPE "PmCompanyEnforcementAction" AS ENUM ('block_access', 'supervisor_override', 'safety_override', 'auto_capa');

CREATE TABLE "company_safety_profiles" (
    "id" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" "PmProjectSafetyPublishStatus" NOT NULL DEFAULT 'draft',
    "corporateRiskLevel" "PmProjectSafetyRiskLevel" NOT NULL DEFAULT 'medium',
    "policiesJson" JSONB NOT NULL DEFAULT '[]',
    "hazardLibraryRef" JSONB NOT NULL DEFAULT '{}',
    "controlLibraryRef" JSONB NOT NULL DEFAULT '{}',
    "trainingMatrixRef" JSONB NOT NULL DEFAULT '{}',
    "ppeStandardsJson" JSONB NOT NULL DEFAULT '[]',
    "emergencyPlansRef" JSONB NOT NULL DEFAULT '[]',
    "sdsLibraryRef" JSONB NOT NULL DEFAULT '{}',
    "equipmentRulesRef" JSONB NOT NULL DEFAULT '{}',
    "zoneTemplatesRef" JSONB NOT NULL DEFAULT '[]',
    "enforcementRulesJson" JSONB NOT NULL DEFAULT '{}',
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "publishedAt" TIMESTAMP(3),
    "publishedById" INTEGER,
    "clientSyncId" TEXT,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "company_safety_profiles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_safety_profile_versions" (
    "id" TEXT NOT NULL,
    "profileId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "snapshotJson" JSONB NOT NULL,
    "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "publishedById" INTEGER,

    CONSTRAINT "company_safety_profile_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_hazard_library" (
    "id" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "profileId" TEXT,
    "category" "PmCompanyHazardCategory" NOT NULL,
    "subcategory" TEXT,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "severity" INTEGER NOT NULL DEFAULT 3,
    "likelihood" INTEGER NOT NULL DEFAULT 3,
    "sifPotential" BOOLEAN NOT NULL DEFAULT false,
    "hecaCategoryKey" TEXT,
    "requiredControlIds" JSONB NOT NULL DEFAULT '[]',
    "requiredTraining" JSONB NOT NULL DEFAULT '[]',
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" "PmProjectSafetyPublishStatus" NOT NULL DEFAULT 'draft',
    "publishedAt" TIMESTAMP(3),
    "syncToProjects" BOOLEAN NOT NULL DEFAULT true,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "clientSyncId" TEXT,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "company_hazard_library_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_control_library" (
    "id" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "profileId" TEXT,
    "controlType" "PmCompanyControlType" NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "controlStrength" INTEGER NOT NULL DEFAULT 3,
    "verificationSteps" JSONB NOT NULL DEFAULT '[]',
    "requiredTraining" JSONB NOT NULL DEFAULT '[]',
    "requiredEquipment" JSONB NOT NULL DEFAULT '[]',
    "hazardCategoryKeys" JSONB NOT NULL DEFAULT '[]',
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" "PmProjectSafetyPublishStatus" NOT NULL DEFAULT 'draft',
    "publishedAt" TIMESTAMP(3),
    "syncToProjects" BOOLEAN NOT NULL DEFAULT true,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "clientSyncId" TEXT,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "company_control_library_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_training_matrix" (
    "id" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "profileId" TEXT,
    "roleType" "PmCompanyTrainingRoleType" NOT NULL,
    "category" "PmCompanyTrainingCategory" NOT NULL,
    "trainingCode" TEXT NOT NULL,
    "trainingName" TEXT NOT NULL,
    "expiresInDays" INTEGER NOT NULL DEFAULT 365,
    "autoAssignRules" JSONB NOT NULL DEFAULT '{}',
    "active" BOOLEAN NOT NULL DEFAULT true,
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" "PmProjectSafetyPublishStatus" NOT NULL DEFAULT 'draft',
    "publishedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "company_training_matrix_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_policies" (
    "id" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "profileId" TEXT,
    "policyType" "PmCompanyPolicyType" NOT NULL DEFAULT 'safety_policy',
    "title" TEXT NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" "PmProjectSafetyPublishStatus" NOT NULL DEFAULT 'draft',
    "storageKey" TEXT,
    "requiresAck" BOOLEAN NOT NULL DEFAULT true,
    "requiresAckForAccess" BOOLEAN NOT NULL DEFAULT false,
    "publishedAt" TIMESTAMP(3),
    "reviewDueAt" TIMESTAMP(3),
    "legacyPolicyId" TEXT,
    "clientSyncId" TEXT,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "company_policies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_policy_versions" (
    "id" TEXT NOT NULL,
    "policyId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "storageKey" TEXT,
    "snapshotJson" JSONB NOT NULL DEFAULT '{}',
    "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "company_policy_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_policy_acknowledgments" (
    "id" TEXT NOT NULL,
    "policyId" TEXT NOT NULL,
    "workerId" INTEGER NOT NULL,
    "acknowledgedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "signatureData" TEXT,

    CONSTRAINT "company_policy_acknowledgments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_sds_library" (
    "id" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "legacySdsId" TEXT,
    "productName" TEXT NOT NULL,
    "manufacturer" TEXT,
    "casNumber" TEXT,
    "whmisClass" TEXT,
    "ppeRequirements" JSONB NOT NULL DEFAULT '[]',
    "firstAidJson" JSONB NOT NULL DEFAULT '{}',
    "handlingJson" JSONB NOT NULL DEFAULT '{}',
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" "PmProjectSafetyPublishStatus" NOT NULL DEFAULT 'draft',
    "expiresAt" TIMESTAMP(3),
    "publishedAt" TIMESTAMP(3),
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "company_sds_library_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_sds_versions" (
    "id" TEXT NOT NULL,
    "sdsId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "snapshotJson" JSONB NOT NULL,
    "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "company_sds_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_emergency_plans" (
    "id" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "planType" "PmEmergencyPlanType" NOT NULL,
    "title" TEXT NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" "PmProjectSafetyPublishStatus" NOT NULL DEFAULT 'draft',
    "contentJson" JSONB NOT NULL DEFAULT '{}',
    "requiresAck" BOOLEAN NOT NULL DEFAULT true,
    "requiresAckForAccess" BOOLEAN NOT NULL DEFAULT false,
    "legacyPlanId" TEXT,
    "publishedAt" TIMESTAMP(3),
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "company_emergency_plans_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_emergency_plan_versions" (
    "id" TEXT NOT NULL,
    "planId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "snapshotJson" JSONB NOT NULL,
    "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "company_emergency_plan_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_equipment_rules" (
    "id" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "profileId" TEXT,
    "ruleKey" TEXT NOT NULL,
    "requiredCerts" JSONB NOT NULL DEFAULT '[]',
    "requiredInspections" JSONB NOT NULL DEFAULT '[]',
    "requiredTraining" JSONB NOT NULL DEFAULT '[]',
    "requiredControls" JSONB NOT NULL DEFAULT '[]',
    "operatorAuthRequired" BOOLEAN NOT NULL DEFAULT true,
    "enforcementAction" "PmCompanyEnforcementAction" NOT NULL DEFAULT 'block_access',
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" "PmProjectSafetyPublishStatus" NOT NULL DEFAULT 'draft',
    "publishedAt" TIMESTAMP(3),
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "company_equipment_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_zone_templates" (
    "id" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "profileId" TEXT,
    "templateCode" TEXT NOT NULL,
    "zoneType" "PmAccessZoneType" NOT NULL,
    "title" TEXT NOT NULL,
    "requiredTraining" JSONB NOT NULL DEFAULT '[]',
    "requiredPpe" JSONB NOT NULL DEFAULT '[]',
    "requiresJha" BOOLEAN NOT NULL DEFAULT false,
    "requiresFlhaHours" INTEGER NOT NULL DEFAULT 24,
    "requiresPermits" JSONB NOT NULL DEFAULT '[]',
    "requiresSdsAck" BOOLEAN NOT NULL DEFAULT false,
    "highRisk" BOOLEAN NOT NULL DEFAULT false,
    "version" INTEGER NOT NULL DEFAULT 1,
    "status" "PmProjectSafetyPublishStatus" NOT NULL DEFAULT 'draft',
    "publishedAt" TIMESTAMP(3),
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "company_zone_templates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_safety_overrides" (
    "id" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "profileId" TEXT,
    "overrideType" "PmCompanySafetyOverrideType" NOT NULL,
    "ruleKey" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "overrideJson" JSONB NOT NULL DEFAULT '{}',
    "expiresAt" TIMESTAMP(3),
    "supervisorSig" TEXT,
    "safetySig" TEXT,
    "approvedById" INTEGER,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "clientSyncId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "company_safety_overrides_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_safety_audit" (
    "id" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "profileId" TEXT,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "actorId" INTEGER,
    "payload" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "company_safety_audit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_safety_offline_cache" (
    "id" TEXT NOT NULL,
    "companyId" INTEGER NOT NULL,
    "cacheKey" TEXT NOT NULL,
    "cacheVersion" INTEGER NOT NULL DEFAULT 1,
    "payload" JSONB NOT NULL,
    "syncedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "company_safety_offline_cache_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "company_safety_profiles_companyId_key" ON "company_safety_profiles"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "company_safety_profiles_clientSyncId_key" ON "company_safety_profiles"("clientSyncId");

-- CreateIndex
CREATE INDEX "company_safety_profiles_status_idx" ON "company_safety_profiles"("status");

-- CreateIndex
CREATE INDEX "company_safety_profiles_corporateRiskLevel_idx" ON "company_safety_profiles"("corporateRiskLevel");

-- CreateIndex
CREATE UNIQUE INDEX "company_safety_profile_versions_profileId_version_key" ON "company_safety_profile_versions"("profileId", "version");

-- CreateIndex
CREATE UNIQUE INDEX "company_hazard_library_clientSyncId_key" ON "company_hazard_library"("clientSyncId");

-- CreateIndex
CREATE INDEX "company_hazard_library_companyId_category_status_idx" ON "company_hazard_library"("companyId", "category", "status");

-- CreateIndex
CREATE INDEX "company_hazard_library_companyId_active_idx" ON "company_hazard_library"("companyId", "active");

-- CreateIndex
CREATE UNIQUE INDEX "company_control_library_clientSyncId_key" ON "company_control_library"("clientSyncId");

-- CreateIndex
CREATE INDEX "company_control_library_companyId_controlType_status_idx" ON "company_control_library"("companyId", "controlType", "status");

-- CreateIndex
CREATE INDEX "company_training_matrix_companyId_roleType_idx" ON "company_training_matrix"("companyId", "roleType");

-- CreateIndex
CREATE UNIQUE INDEX "company_training_matrix_companyId_roleType_trainingCode_key" ON "company_training_matrix"("companyId", "roleType", "trainingCode");

-- CreateIndex
CREATE UNIQUE INDEX "company_policies_clientSyncId_key" ON "company_policies"("clientSyncId");

-- CreateIndex
CREATE INDEX "company_policies_companyId_policyType_status_idx" ON "company_policies"("companyId", "policyType", "status");

-- CreateIndex
CREATE UNIQUE INDEX "company_policy_versions_policyId_version_key" ON "company_policy_versions"("policyId", "version");

-- CreateIndex
CREATE INDEX "company_policy_acknowledgments_workerId_idx" ON "company_policy_acknowledgments"("workerId");

-- CreateIndex
CREATE UNIQUE INDEX "company_policy_acknowledgments_policyId_workerId_key" ON "company_policy_acknowledgments"("policyId", "workerId");

-- CreateIndex
CREATE UNIQUE INDEX "company_sds_library_legacySdsId_key" ON "company_sds_library"("legacySdsId");

-- CreateIndex
CREATE INDEX "company_sds_library_companyId_productName_idx" ON "company_sds_library"("companyId", "productName");

-- CreateIndex
CREATE INDEX "company_sds_library_expiresAt_idx" ON "company_sds_library"("expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "company_sds_versions_sdsId_version_key" ON "company_sds_versions"("sdsId", "version");

-- CreateIndex
CREATE INDEX "company_emergency_plans_companyId_planType_idx" ON "company_emergency_plans"("companyId", "planType");

-- CreateIndex
CREATE UNIQUE INDEX "company_emergency_plan_versions_planId_version_key" ON "company_emergency_plan_versions"("planId", "version");

-- CreateIndex
CREATE UNIQUE INDEX "company_equipment_rules_companyId_ruleKey_key" ON "company_equipment_rules"("companyId", "ruleKey");

-- CreateIndex
CREATE UNIQUE INDEX "company_zone_templates_companyId_templateCode_key" ON "company_zone_templates"("companyId", "templateCode");

-- CreateIndex
CREATE UNIQUE INDEX "company_safety_overrides_clientSyncId_key" ON "company_safety_overrides"("clientSyncId");

-- CreateIndex
CREATE INDEX "company_safety_overrides_companyId_overrideType_active_idx" ON "company_safety_overrides"("companyId", "overrideType", "active");

-- CreateIndex
CREATE INDEX "company_safety_audit_companyId_createdAt_idx" ON "company_safety_audit"("companyId", "createdAt");

-- CreateIndex
CREATE INDEX "company_safety_audit_entityType_entityId_createdAt_idx" ON "company_safety_audit"("entityType", "entityId", "createdAt");

-- CreateIndex
CREATE INDEX "company_safety_offline_cache_companyId_updatedAt_idx" ON "company_safety_offline_cache"("companyId", "updatedAt");

-- CreateIndex
CREATE UNIQUE INDEX "company_safety_offline_cache_companyId_cacheKey_key" ON "company_safety_offline_cache"("companyId", "cacheKey");

ALTER TABLE "company_safety_profiles" ADD CONSTRAINT "company_safety_profiles_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_safety_profiles" ADD CONSTRAINT "company_safety_profiles_publishedById_fkey" FOREIGN KEY ("publishedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_safety_profile_versions" ADD CONSTRAINT "company_safety_profile_versions_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "company_safety_profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_safety_profile_versions" ADD CONSTRAINT "company_safety_profile_versions_publishedById_fkey" FOREIGN KEY ("publishedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_hazard_library" ADD CONSTRAINT "company_hazard_library_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_hazard_library" ADD CONSTRAINT "company_hazard_library_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "company_safety_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_control_library" ADD CONSTRAINT "company_control_library_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_control_library" ADD CONSTRAINT "company_control_library_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "company_safety_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_training_matrix" ADD CONSTRAINT "company_training_matrix_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_training_matrix" ADD CONSTRAINT "company_training_matrix_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "company_safety_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_policies" ADD CONSTRAINT "company_policies_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_policies" ADD CONSTRAINT "company_policies_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "company_safety_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_policy_versions" ADD CONSTRAINT "company_policy_versions_policyId_fkey" FOREIGN KEY ("policyId") REFERENCES "company_policies"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_policy_acknowledgments" ADD CONSTRAINT "company_policy_acknowledgments_policyId_fkey" FOREIGN KEY ("policyId") REFERENCES "company_policies"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_policy_acknowledgments" ADD CONSTRAINT "company_policy_acknowledgments_workerId_fkey" FOREIGN KEY ("workerId") REFERENCES "Worker"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_sds_library" ADD CONSTRAINT "company_sds_library_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_sds_versions" ADD CONSTRAINT "company_sds_versions_sdsId_fkey" FOREIGN KEY ("sdsId") REFERENCES "company_sds_library"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_emergency_plans" ADD CONSTRAINT "company_emergency_plans_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_emergency_plan_versions" ADD CONSTRAINT "company_emergency_plan_versions_planId_fkey" FOREIGN KEY ("planId") REFERENCES "company_emergency_plans"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_equipment_rules" ADD CONSTRAINT "company_equipment_rules_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_equipment_rules" ADD CONSTRAINT "company_equipment_rules_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "company_safety_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_zone_templates" ADD CONSTRAINT "company_zone_templates_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_zone_templates" ADD CONSTRAINT "company_zone_templates_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "company_safety_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_safety_overrides" ADD CONSTRAINT "company_safety_overrides_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_safety_overrides" ADD CONSTRAINT "company_safety_overrides_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "company_safety_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_safety_overrides" ADD CONSTRAINT "company_safety_overrides_approvedById_fkey" FOREIGN KEY ("approvedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_safety_audit" ADD CONSTRAINT "company_safety_audit_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "company_safety_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_safety_audit" ADD CONSTRAINT "company_safety_audit_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_safety_offline_cache" ADD CONSTRAINT "company_safety_offline_cache_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;