/**
 * VeriForge token facade — industrial safety system + motion/iconography extensions.
 */
export {
  COLORS,
  GEOMETRY,
  TYPOGRAPHY,
  SPACING,
  SHADOWS,
  BORDERS,
  veriforgeTokens as forgedMetalTokens,
  veriforgeCssVars as forgedMetalCssVars,
  colors,
  geometry,
  typography,
  spacing,
  shadows,
  borders,
} from "@/src/theme/veriforge-tokens";

import {
  COLORS,
  GEOMETRY,
  TYPOGRAPHY,
  SPACING,
  SHADOWS,
  BORDERS,
  veriforgeCssVars as forgedCssVars,
} from "@/src/theme/veriforge-tokens";

/** Full product token bag (industrial safety core + motion/iconography extensions) */
export const veriforgeTokens = {
  color: {
    forgeRed: COLORS.safetyBlue,
    safetyBlue: COLORS.safetyBlue,
    inspectionTeal: COLORS.inspectionTeal,
    deepSlate: COLORS.deepSlate,
    graphite: COLORS.graphite,
    ironBlack: COLORS.ironBlack,
    steelGrey: COLORS.steelGrey,
    safetyWhite: COLORS.safetyWhite,
    mutedAmber: COLORS.mutedAmber,
    softGreen: COLORS.softGreen,
    criticalAlert: COLORS.criticalAlert,
    glowRed: "rgba(30,111,184,0.35)",
    glowWhite: "rgba(255,255,255,0.12)",
  },
  colors: COLORS,
  geometry: GEOMETRY,
  typography: {
    headingFont: TYPOGRAPHY.headingFont,
    bodyFont: TYPOGRAPHY.bodyFont,
    fontPrimary: TYPOGRAPHY.headingFont,
    headingWeight: TYPOGRAPHY.headingWeight,
    bodyWeight: TYPOGRAPHY.bodyWeight,
    headingTransform: "none" as const,
    bodyTransform: "none" as const,
  },
  spacing: {
    xs: SPACING.xs,
    sm: SPACING.sm,
    md: SPACING.md,
    lg: SPACING.lg,
    xl: SPACING.xl,
    spacingXS: SPACING.xs,
    spacingSM: SPACING.sm,
    spacingMD: SPACING.md,
    spacingLG: SPACING.lg,
    spacingXL: SPACING.xl,
  },
  radius: {
    angularRadius: GEOMETRY.angularRadius,
    bevelEdge: GEOMETRY.bevelEdge,
    cardBevel: GEOMETRY.cardBevel,
    radiusNone: GEOMETRY.angularRadius,
    radiusSM: "3px",
    radiusMD: "4px",
  },
  shadow: {
    metallicShadow: SHADOWS.metallicShadow,
    steelShadow: SHADOWS.steelShadow,
    shadowMetal: SHADOWS.metallicShadow,
    shadowSteel: SHADOWS.steelShadow,
  },
  shadows: SHADOWS,
  border: {
    redAccentBorder: BORDERS.accentBorder,
    steelBorder: BORDERS.steelBorder,
    borderSteel: BORDERS.steelBorder,
    borderRed: BORDERS.accentBorder,
    borderCritical: BORDERS.criticalBorder,
  },
  borders: BORDERS,
  effect: {
    glowPrimary: SHADOWS.metallicShadow,
    glowSecondary: SHADOWS.steelShadow,
    metallicGradient: COLORS.metallicGradient,
  },
  motion: {
    durationFast: "120ms",
    durationMedium: "240ms",
    durationHeavy: "400ms",
    easeAngular: "cubic-bezier(0.2, 0.0, 0.0, 1)",
    easeIndustrial: "cubic-bezier(0.33, 0.0, 0.2, 1)",
    easeRebound: "cubic-bezier(0.34, 1.2, 0.64, 1)",
  },
  animation: {
    primitives: [
      "angularSlide",
      "metallicFade",
      "accentGlowPulse",
      "bevelShift",
      "industrialDrop",
    ] as const,
    components: [
      "buttons",
      "cards",
      "panels",
      "modals",
      "workflow",
      "charts",
    ] as const,
    durationFastMin: 120,
    durationFastMax: 120,
    durationMediumMin: 240,
    durationMediumMax: 240,
    durationHeavyMin: 400,
    durationHeavyMax: 400,
  },
  iconography: {
    strokeHeavy: 1.75,
    strokeAccent: 1.5,
    sizeMin: 16,
    sizeMax: 128,
    sizeDefault: 24,
    corner: "angular",
    fillMetallic: COLORS.metallicGradient,
    outlineSteel: COLORS.steelGrey,
    accentRed: COLORS.safetyBlue,
    accentBlue: COLORS.safetyBlue,
    baseBlack: COLORS.ironBlack,
    contrastWhite: COLORS.safetyWhite,
  },
} as const;

export const veriforgeCssVars = {
  ...forgedCssVars,
  "--vf-color-glow-red": veriforgeTokens.color.glowRed,
  "--vf-color-glow-white": veriforgeTokens.color.glowWhite,
  "--vf-radius-sm": veriforgeTokens.radius.radiusSM,
  "--vf-radius-md": veriforgeTokens.radius.radiusMD,
  "--vf-effect-glow-primary": veriforgeTokens.effect.glowPrimary,
  "--vf-effect-glow-secondary": veriforgeTokens.effect.glowSecondary,
  "--vf-motion-fast": veriforgeTokens.motion.durationFast,
  "--vf-motion-medium": veriforgeTokens.motion.durationMedium,
  "--vf-motion-heavy": veriforgeTokens.motion.durationHeavy,
  "--vf-ease-angular": veriforgeTokens.motion.easeAngular,
  "--vf-ease-industrial": veriforgeTokens.motion.easeIndustrial,
  "--vf-ease-rebound": veriforgeTokens.motion.easeRebound,
  "--vf-icon-stroke-heavy": String(veriforgeTokens.iconography.strokeHeavy),
  "--vf-icon-stroke-accent": String(veriforgeTokens.iconography.strokeAccent),
  "--vf-icon-size-default": `${veriforgeTokens.iconography.sizeDefault}px`,
  "--vf-icon-outline": veriforgeTokens.iconography.outlineSteel,
  "--vf-icon-accent": veriforgeTokens.iconography.accentBlue,
  "--vf-icon-base": veriforgeTokens.iconography.baseBlack,
  "--vf-icon-contrast": veriforgeTokens.iconography.contrastWhite,
} as const;

export type VeriForgeTokenVarName = keyof typeof veriforgeCssVars;
