/**
 * Authoritative VeriSuite SMS QA catalog — every page, AI behavior, API endpoint.
 * Consumed by unit/smoke tests and the QA canvas.
 */

export const SMS_QA_PAGES = [
  { id: 'home', route: '/pm', assembled: 'home', layoutBands: ['controls', 'kpi', 'trend', 'detail', 'narrative'] },
  { id: 'flha', route: '/pm/jha-flha', assembled: 'flha', layoutBands: ['controls', 'kpi', 'trend', 'detail', 'narrative'] },
  { id: 'jha', route: '/pm/jha-flha', assembled: 'jha', layoutBands: ['controls', 'kpi', 'trend', 'detail', 'narrative'] },
  { id: 'erp', route: '/pm/emergency-response', assembled: 'erp', layoutBands: ['controls', 'kpi', 'trend', 'detail', 'narrative'] },
  { id: 'inspections', route: '/pm/inspections', assembled: 'inspections', layoutBands: ['controls', 'kpi', 'trend', 'detail', 'narrative'] },
  { id: 'incidents', route: '/pm/incidents', assembled: 'incidents', layoutBands: ['controls', 'kpi', 'trend', 'detail', 'narrative'] },
  { id: 'meetings', route: '/pm/safety-meetings', assembled: 'meetings', layoutBands: ['controls', 'kpi', 'trend', 'detail', 'narrative'] },
  { id: 'actions', route: '/pm/action-management', assembled: 'actions', layoutBands: ['controls', 'kpi', 'trend', 'detail', 'narrative'] },
  { id: 'competency', route: '/pm/training', assembled: 'competency', layoutBands: ['controls', 'kpi', 'trend', 'detail', 'narrative'] },
  { id: 'predictive', route: '/pm/predictive-safety-analytics', assembled: null, layoutBands: ['controls', 'kpi', 'narrative'] },
  { id: 'sms-ops', route: '/pm/sms-ops', assembled: null, layoutBands: ['controls', 'kpi', 'trend', 'detail', 'narrative'] },
  { id: 'sms-dashboards', route: '/pm/sms-dashboards', assembled: null, layoutBands: ['gallery'] },
  { id: 'sms-mockups', route: '/pm/sms-mockups', assembled: null, layoutBands: ['gallery'] },
] as const;

export const SMS_QA_AI_BEHAVIORS = [
  { id: 'AI-01', name: 'Smart Insights (home)', page: 'home', tier: 'D1' },
  { id: 'AI-02', name: 'FLHA hazard prediction', page: 'jha-flha', tier: 'D0' },
  { id: 'AI-03', name: 'FLHA scoring', page: 'jha-flha', tier: 'D1' },
  { id: 'AI-04', name: 'JHA auto-suggest', page: 'jha-flha', tier: 'D0' },
  { id: 'AI-05', name: 'JHA risk rank', page: 'jha-flha', tier: 'D1' },
  { id: 'AI-06', name: 'ERP generation', page: 'emergency', tier: 'D0' },
  { id: 'AI-07', name: 'ERP simulation', page: 'emergency', tier: 'D0' },
  { id: 'AI-08', name: 'Inspection focus areas', page: 'inspections', tier: 'D0' },
  { id: 'AI-09', name: 'Inspection quality', page: 'inspections', tier: 'D1' },
  { id: 'AI-10', name: 'Incident investigation helper', page: 'incidents', tier: 'D0' },
  { id: 'AI-11', name: 'Root cause suggestion', page: 'incidents', tier: 'D0' },
  { id: 'AI-12', name: 'Corrective action suggestion', page: 'actions', tier: 'D0' },
  { id: 'AI-13', name: 'Preventive action suggestion', page: 'actions', tier: 'D0' },
  { id: 'AI-14', name: 'Safety meeting topic generation', page: 'meetings', tier: 'D0' },
  { id: 'AI-15', name: 'Competency risk forecasting', page: 'training', tier: 'D1' },
  { id: 'AI-16', name: 'Industry benchmarking', page: 'home', tier: 'D1' },
  { id: 'AI-17', name: 'Cross-page intelligence', page: 'home', tier: 'D1' },
  { id: 'AI-18', name: 'Regional drilldown intelligence', page: 'regional', tier: 'D1' },
] as const;

/** Full API Spec — method + path relative to /api/v1/sms */
export const SMS_QA_ENDPOINTS = [
  { method: 'GET', path: '/health', auth: false },
  { method: 'GET', path: '/ops/ai-decisions', auth: true },
  { method: 'POST', path: '/ops/alert-test', auth: true },
  { method: 'GET', path: '/ops/monitoring', auth: true },
  { method: 'GET', path: '/ops/monitoring/:domainId', auth: true },
  { method: 'GET', path: '/ops/ai-performance', auth: true },
  { method: 'GET', path: '/ops/compliance', auth: true },
  { method: 'GET', path: '/ops/release-cycle', auth: true },
  { method: 'POST', path: '/metrics/recompute', auth: true },
  { method: 'GET', path: '/dashboard/home', auth: true },
  { method: 'GET', path: '/dashboard/modules/:module', auth: true },
  { method: 'POST', path: '/flha', auth: true },
  { method: 'GET', path: '/flha', auth: true },
  { method: 'GET', path: '/flha/:id', auth: true },
  { method: 'PUT', path: '/flha/:id', auth: true },
  { method: 'POST', path: '/flha/:id/score', auth: true },
  { method: 'GET', path: '/jha/templates', auth: true },
  { method: 'GET', path: '/jha/templates/:templateId', auth: true },
  { method: 'POST', path: '/jha', auth: true },
  { method: 'POST', path: '/jha/suggest', auth: true },
  { method: 'POST', path: '/jha/:id/risk-rank', auth: true },
  { method: 'PUT', path: '/jha/:id', auth: true },
  { method: 'GET', path: '/jha', auth: true },
  { method: 'GET', path: '/jha/:id', auth: true },
  { method: 'GET', path: '/ems', auth: true },
  { method: 'POST', path: '/erp/generate', auth: true },
  { method: 'POST', path: '/erp', auth: true },
  { method: 'POST', path: '/erp/:id/simulate', auth: true },
  { method: 'POST', path: '/erp/:id/drills', auth: true },
  { method: 'PUT', path: '/erp/drills/:drillId/roster/:personId', auth: true },
  { method: 'GET', path: '/erp', auth: true },
  { method: 'GET', path: '/erp/:id', auth: true },
  { method: 'POST', path: '/inspections', auth: true },
  { method: 'GET', path: '/inspections/trends', auth: true },
  { method: 'POST', path: '/inspections/focus-packs', auth: true },
  { method: 'GET', path: '/inspections', auth: true },
  { method: 'POST', path: '/inspections/:id/score', auth: true },
  { method: 'POST', path: '/incidents', auth: true },
  { method: 'GET', path: '/incidents/log', auth: true },
  { method: 'GET', path: '/incidents/metrics', auth: true },
  { method: 'GET', path: '/incidents/:id/investigation', auth: true },
  { method: 'PUT', path: '/incidents/:id/investigation', auth: true },
  { method: 'POST', path: '/incidents/:id/investigation/helper', auth: true },
  { method: 'POST', path: '/incidents/:id/root-causes/suggest', auth: true },
  { method: 'GET', path: '/incidents/:id', auth: true },
  { method: 'POST', path: '/meetings/topics/generate', auth: true },
  { method: 'POST', path: '/meetings', auth: true },
  { method: 'PUT', path: '/meetings/:id', auth: true },
  { method: 'GET', path: '/meetings', auth: true },
  { method: 'POST', path: '/meetings/:id/attendees/sign-in', auth: true },
  { method: 'POST', path: '/actions/suggest', auth: true },
  { method: 'POST', path: '/actions', auth: true },
  { method: 'GET', path: '/actions/metrics', auth: true },
  { method: 'GET', path: '/actions', auth: true },
  { method: 'PUT', path: '/actions/:id', auth: true },
  { method: 'GET', path: '/actions/:id', auth: true },
  { method: 'GET', path: '/competency/metrics', auth: true },
  { method: 'GET', path: '/competency/gaps', auth: true },
  { method: 'POST', path: '/competency/forecast', auth: true },
  { method: 'GET', path: '/benchmarks/industry', auth: true },
  { method: 'GET', path: '/regions/tree', auth: true },
  { method: 'GET', path: '/regions/:geoCode/metrics', auth: true },
  { method: 'GET', path: '/regions/:geoCode/insights', auth: true },
  { method: 'GET', path: '/regions/:geoCode/projects', auth: true },
  { method: 'GET', path: '/intelligence/catalog', auth: true },
  { method: 'GET', path: '/intelligence', auth: true },
  { method: 'POST', path: '/intelligence/run', auth: true },
  { method: 'GET', path: '/intelligence/insights/home', auth: true },
  { method: 'POST', path: '/intelligence/accept', auth: true },
  { method: 'POST', path: '/intelligence/dismiss', auth: true },
  { method: 'GET', path: '/flows', auth: true },
  { method: 'GET', path: '/flows/:flowId', auth: true },
  { method: 'POST', path: '/flows/:flowId/progress', auth: true },
  { method: 'GET', path: '/data-model', auth: true },
  { method: 'GET', path: '/data-model/retention', auth: true },
  { method: 'POST', path: '/ops/retention/purge', auth: true },
] as const;

export const SMS_QA_UI_COMPONENTS = [
  'KpiTile',
  'TrendPanel',
  'AiInsightPanel',
  'InsightStrip',
  'LeadingHeatmap',
  'RegionalMapPanel',
  'RiskGauge',
  'SeverityBars',
  'BubbleChart',
  'RootCauseActionFlow',
  'ActionAgingHistogram',
  'InspectionGrid',
  'InspectionTrendCard',
  'MeetingTopicCards',
  'ErpScenarioCards',
  'JhaHazardBlocks',
  'FlhaEnergyWheel',
  'ComparisonPanel',
  'VsDashboardShell',
  'VsSection',
] as const;

export const SMS_QA_ROLES = [
  'SUPER_ADMIN',
  'ADMIN',
  'COMPANY_ADMIN',
  'PROJECT_MANAGER',
  'SUPERVISOR',
  'WORKER',
  'CONTRACTOR_ADMIN',
  'CONTRACTOR_USER',
] as const;

export const SMS_QA_DESIGN_LOCK = {
  version: '1.1.0-final',
  status: 'FINALIZED',
  palette: {
    navy: '#0D1B2A',
    slate: '#1B263B',
    electricBlue: '#00A3FF',
  },
  layoutOrder: ['controls', 'kpi', 'trend', 'detail', 'narrative'] as const,
  mobileBreakpoints: { mobile: 375, tablet: 768, desktop: 1280 },
  touchTargetMin: 44,
  aggregateCacheTtlMs: 45_000,
  analyticsP95Ms: 400,
  aiSuggestP95Ms: 2000,
};
