import { API_V1_PREFIX } from './routes';

/** Versioned route segments (§9) — single source for new controllers. */
export const V1_ROUTES = {
  workers: `${API_V1_PREFIX}/workers`,
  equipment: `${API_V1_PREFIX}/equipment`,
  training: `${API_V1_PREFIX}/training`,
  providers: `${API_V1_PREFIX}/providers`,
  unionHalls: `${API_V1_PREFIX}/union-halls`,
  companies: `${API_V1_PREFIX}/companies`,
  projects: `${API_V1_PREFIX}/projects`,
  inspections: `${API_V1_PREFIX}/inspections`,
  competency: `${API_V1_PREFIX}/competency`,
  compliance: `${API_V1_PREFIX}/compliance`,
  wallet: `${API_V1_PREFIX}/wallet`,
  qr: `${API_V1_PREFIX}/qr`,
  sync: `${API_V1_PREFIX}/sync`,
  dashboard: `${API_V1_PREFIX}/dashboard`,
  core: `${API_V1_PREFIX}/core`,
  reporting: `${API_V1_PREFIX}/reporting`,
  field: `${API_V1_PREFIX}/field`,
  intelligence: `${API_V1_PREFIX}/intelligence`,
  vision: `${API_V1_PREFIX}/vision`,
  twins: `${API_V1_PREFIX}/twins`,
  safety: `${API_V1_PREFIX}/safety`,
  scheduling: `${API_V1_PREFIX}/scheduling`,
  operations: `${API_V1_PREFIX}/operations`,
  enterprise: `${API_V1_PREFIX}/enterprise`,
  commandCenter: `${API_V1_PREFIX}/command-center`,
  brain: `${API_V1_PREFIX}/brain`,
  globalNetwork: `${API_V1_PREFIX}/global-network`,
  industryEcosystem: `${API_V1_PREFIX}/industry-ecosystem`,
  marketplace: `${API_V1_PREFIX}/marketplace`,
  interplanetary: `${API_V1_PREFIX}/interplanetary`,
  interstellar: `${API_V1_PREFIX}/interstellar`,
  civilization: `${API_V1_PREFIX}/civilization`,
} as const;
