-- PM Project Safety Context Engine

CREATE TYPE "PmProjectSafetyRiskLevel" AS ENUM ('low', 'medium', 'high', 'critical');
CREATE TYPE "PmProjectSafetyPublishStatus" AS ENUM ('draft', 'published', 'archived');
CREATE TYPE "PmProjectHazardCategory" AS ENUM ('energy', 'environmental', 'equipment', 'chemical', 'behavioral', 'site_specific');
CREATE TYPE "PmProjectControlType" AS ENUM ('engineering', 'administrative', 'ppe', 'equipment');
CREATE TYPE "PmProjectSafetyOverrideRuleType" AS ENUM ('profile', 'zone', 'equipment', 'training', 'emergency', 'hazard', 'control');

CREATE TABLE "pm_project_safety_profiles" (
  "id" TEXT NOT NULL,
  "companyId" INTEGER NOT NULL,
  "projectId" INTEGER NOT NULL,
  "version" INTEGER NOT NULL DEFAULT 1,
  "status" "PmProjectSafetyPublishStatus" NOT NULL DEFAULT 'draft',
  "riskLevel" "PmProjectSafetyRiskLevel" NOT NULL DEFAULT 'medium',
  "projectType" TEXT,
  "scopeOfWorkJson" JSONB NOT NULL DEFAULT '{}',
  "requiredJhaTypes" JSONB NOT NULL DEFAULT '[]',
  "requiredInspections" JSONB NOT NULL DEFAULT '[]',
  "requiredTraining" JSONB NOT NULL DEFAULT '[]',
  "requiredEquipmentCerts" JSONB NOT NULL DEFAULT '[]',
  "requiredPpe" JSONB NOT NULL DEFAULT '[]',
  "requiredEmergencyPlans" JSONB NOT NULL DEFAULT '[]',
  "requiredSdsAcks" JSONB NOT NULL DEFAULT '[]',
  "requiredToolboxTalks" JSONB NOT NULL DEFAULT '[]',
  "enforcementRulesJson" JSONB NOT NULL DEFAULT '{}',
  "zoneRulesJson" JSONB NOT NULL DEFAULT '[]',
  "equipmentRulesJson" JSONB NOT NULL DEFAULT '{}',
  "trainingRulesJson" JSONB NOT NULL DEFAULT '{}',
  "emergencyRulesJson" JSONB NOT NULL DEFAULT '{}',
  "environmentalJson" JSONB NOT NULL DEFAULT '{}',
  "subcontractorIds" JSONB NOT NULL DEFAULT '[]',
  "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
  "publishedAt" TIMESTAMP(3),
  "publishedById" INTEGER,
  "clientSyncId" TEXT,
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "pm_project_safety_profiles_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "pm_project_safety_profiles_projectId_key" ON "pm_project_safety_profiles"("projectId");
CREATE UNIQUE INDEX "pm_project_safety_profiles_clientSyncId_key" ON "pm_project_safety_profiles"("clientSyncId");
CREATE INDEX "pm_project_safety_profiles_companyId_status_idx" ON "pm_project_safety_profiles"("companyId", "status");
CREATE INDEX "pm_project_safety_profiles_riskLevel_idx" ON "pm_project_safety_profiles"("riskLevel");
ALTER TABLE "pm_project_safety_profiles" ADD CONSTRAINT "pm_project_safety_profiles_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pm_project_safety_profiles" ADD CONSTRAINT "pm_project_safety_profiles_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pm_project_safety_profiles" ADD CONSTRAINT "pm_project_safety_profiles_publishedById_fkey" FOREIGN KEY ("publishedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "pm_project_safety_profile_versions" (
  "id" TEXT NOT NULL,
  "profileId" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "snapshotJson" JSONB NOT NULL,
  "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "publishedById" INTEGER,
  CONSTRAINT "pm_project_safety_profile_versions_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "pm_project_safety_profile_versions_profileId_version_key" ON "pm_project_safety_profile_versions"("profileId", "version");
CREATE INDEX "pm_project_safety_profile_versions_profileId_publishedAt_idx" ON "pm_project_safety_profile_versions"("profileId", "publishedAt");
ALTER TABLE "pm_project_safety_profile_versions" ADD CONSTRAINT "pm_project_safety_profile_versions_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "pm_project_safety_profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pm_project_safety_profile_versions" ADD CONSTRAINT "pm_project_safety_profile_versions_publishedById_fkey" FOREIGN KEY ("publishedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "pm_project_hazards" (
  "id" TEXT NOT NULL,
  "companyId" INTEGER NOT NULL,
  "projectId" INTEGER NOT NULL,
  "profileId" TEXT,
  "category" "PmProjectHazardCategory" NOT NULL,
  "subcategory" TEXT,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "severity" INTEGER NOT NULL DEFAULT 3,
  "likelihood" INTEGER NOT NULL DEFAULT 3,
  "sifPotential" BOOLEAN NOT NULL DEFAULT false,
  "hecaCategoryKey" TEXT,
  "requiredControlIds" JSONB NOT NULL DEFAULT '[]',
  "sourceType" TEXT,
  "sourceId" TEXT,
  "version" INTEGER NOT NULL DEFAULT 1,
  "status" "PmProjectSafetyPublishStatus" NOT NULL DEFAULT 'draft',
  "publishedAt" TIMESTAMP(3),
  "active" BOOLEAN NOT NULL DEFAULT true,
  "clientSyncId" TEXT,
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "pm_project_hazards_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "pm_project_hazards_clientSyncId_key" ON "pm_project_hazards"("clientSyncId");
CREATE INDEX "pm_project_hazards_projectId_category_status_idx" ON "pm_project_hazards"("projectId", "category", "status");
CREATE INDEX "pm_project_hazards_projectId_active_idx" ON "pm_project_hazards"("projectId", "active");
ALTER TABLE "pm_project_hazards" ADD CONSTRAINT "pm_project_hazards_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pm_project_hazards" ADD CONSTRAINT "pm_project_hazards_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pm_project_hazards" ADD CONSTRAINT "pm_project_hazards_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "pm_project_safety_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "pm_project_controls" (
  "id" TEXT NOT NULL,
  "companyId" INTEGER NOT NULL,
  "projectId" INTEGER NOT NULL,
  "profileId" TEXT,
  "controlType" "PmProjectControlType" NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "hazardCategoryKeys" JSONB NOT NULL DEFAULT '[]',
  "ppeRequired" BOOLEAN NOT NULL DEFAULT false,
  "equipmentRuleJson" JSONB NOT NULL DEFAULT '{}',
  "version" INTEGER NOT NULL DEFAULT 1,
  "status" "PmProjectSafetyPublishStatus" NOT NULL DEFAULT 'draft',
  "publishedAt" TIMESTAMP(3),
  "active" BOOLEAN NOT NULL DEFAULT true,
  "clientSyncId" TEXT,
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "pm_project_controls_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "pm_project_controls_clientSyncId_key" ON "pm_project_controls"("clientSyncId");
CREATE INDEX "pm_project_controls_projectId_controlType_status_idx" ON "pm_project_controls"("projectId", "controlType", "status");
ALTER TABLE "pm_project_controls" ADD CONSTRAINT "pm_project_controls_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pm_project_controls" ADD CONSTRAINT "pm_project_controls_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pm_project_controls" ADD CONSTRAINT "pm_project_controls_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "pm_project_safety_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "pm_project_safety_overrides" (
  "id" TEXT NOT NULL,
  "companyId" INTEGER NOT NULL,
  "projectId" INTEGER NOT NULL,
  "profileId" TEXT,
  "ruleType" "PmProjectSafetyOverrideRuleType" NOT NULL,
  "ruleKey" TEXT NOT NULL,
  "overrideJson" JSONB NOT NULL DEFAULT '{}',
  "reason" TEXT NOT NULL,
  "expiresAt" TIMESTAMP(3),
  "approvedById" INTEGER,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "clientSyncId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pm_project_safety_overrides_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "pm_project_safety_overrides_clientSyncId_key" ON "pm_project_safety_overrides"("clientSyncId");
CREATE INDEX "pm_project_safety_overrides_projectId_ruleType_active_idx" ON "pm_project_safety_overrides"("projectId", "ruleType", "active");
CREATE INDEX "pm_project_safety_overrides_expiresAt_idx" ON "pm_project_safety_overrides"("expiresAt");
ALTER TABLE "pm_project_safety_overrides" ADD CONSTRAINT "pm_project_safety_overrides_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pm_project_safety_overrides" ADD CONSTRAINT "pm_project_safety_overrides_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pm_project_safety_overrides" ADD CONSTRAINT "pm_project_safety_overrides_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "pm_project_safety_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "pm_project_safety_overrides" ADD CONSTRAINT "pm_project_safety_overrides_approvedById_fkey" FOREIGN KEY ("approvedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "pm_project_safety_context_audit" (
  "id" TEXT NOT NULL,
  "profileId" TEXT,
  "projectId" INTEGER,
  "entityType" TEXT NOT NULL,
  "entityId" TEXT NOT NULL,
  "eventType" TEXT NOT NULL,
  "actorId" INTEGER,
  "payload" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "pm_project_safety_context_audit_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "pm_project_safety_context_audit_projectId_createdAt_idx" ON "pm_project_safety_context_audit"("projectId", "createdAt");
CREATE INDEX "pm_project_safety_context_audit_entityType_entityId_createdAt_idx" ON "pm_project_safety_context_audit"("entityType", "entityId", "createdAt");
ALTER TABLE "pm_project_safety_context_audit" ADD CONSTRAINT "pm_project_safety_context_audit_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "pm_project_safety_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "pm_project_safety_context_audit" ADD CONSTRAINT "pm_project_safety_context_audit_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "pm_project_safety_offline_cache" (
  "id" TEXT NOT NULL,
  "projectId" INTEGER NOT NULL,
  "cacheKey" TEXT NOT NULL,
  "cacheVersion" INTEGER NOT NULL DEFAULT 1,
  "payload" JSONB NOT NULL,
  "syncedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "pm_project_safety_offline_cache_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "pm_project_safety_offline_cache_projectId_cacheKey_key" ON "pm_project_safety_offline_cache"("projectId", "cacheKey");
CREATE INDEX "pm_project_safety_offline_cache_projectId_updatedAt_idx" ON "pm_project_safety_offline_cache"("projectId", "updatedAt");
ALTER TABLE "pm_project_safety_offline_cache" ADD CONSTRAINT "pm_project_safety_offline_cache_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
