apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "veri-agent.fullname" . }}
  labels:
    {{- include "veri-agent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "veri-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "veri-agent.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.service.port | quote }}
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: veri-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "veri-agent.fullname" . }}
            - secretRef:
                name: {{ .Values.existingSecret }}
          volumeMounts:
            - name: tenant-overrides
              mountPath: /app/config/policies/tenant-overrides.json
              subPath: tenant-overrides.json
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: tenant-overrides
          configMap:
            name: {{ include "veri-agent.fullname" . }}-tenant-overrides
